// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniThesis.Infrastructure.Persistence;

#nullable disable

namespace UniThesis.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(UniThesisDbContext))]
    partial class UniThesisDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Pessoa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("TipoPessoa")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Pessoas");

                    b.HasDiscriminator<string>("TipoPessoa").HasValue("Pessoa");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("UniThesis.Domain.Ideas.IdeiaDePesquisa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Resumo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ideias");
                });

            modelBuilder.Entity("UniThesis.Domain.Projects.Projeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("IdeiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OrientadorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Projetos");
                });

            modelBuilder.Entity("UniThesis.Domain.Users.UserAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("UniThesis.Domain.Users.Aluno", b =>
                {
                    b.HasBaseType("Pessoa");

                    b.Property<string>("Matricula")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Aluno");
                });

            modelBuilder.Entity("UniThesis.Domain.Users.Coordenador", b =>
                {
                    b.HasBaseType("Pessoa");

                    b.HasDiscriminator().HasValue("Coordenador");
                });

            modelBuilder.Entity("UniThesis.Domain.Users.Professor", b =>
                {
                    b.HasBaseType("Pessoa");

                    b.Property<string>("AreaAtuacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Professor");
                });

            modelBuilder.Entity("UniThesis.Domain.Ideas.IdeiaDePesquisa", b =>
                {
                    b.OwnsMany("UniThesis.Domain.Ideas.Avaliacao", "Avaliacoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("DataAvaliacao")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Feedback")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("IdeiaId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Nota")
                                .HasColumnType("int");

                            b1.Property<Guid>("ProfessorId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("IdeiaId");

                            b1.ToTable("Avaliacao");

                            b1.WithOwner()
                                .HasForeignKey("IdeiaId");
                        });

                    b.Navigation("Avaliacoes");
                });

            modelBuilder.Entity("UniThesis.Domain.Projects.Projeto", b =>
                {
                    b.OwnsMany("UniThesis.Domain.Projects.DocumentoVersionado", "Documentos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("DataSubmissao")
                                .HasColumnType("datetime2");

                            b1.Property<string>("NomeArquivo")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Path")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("ProjetoId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Versao")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("ProjetoId");

                            b1.ToTable("DocumentoVersionado");

                            b1.WithOwner()
                                .HasForeignKey("ProjetoId");
                        });

                    b.Navigation("Documentos");
                });
#pragma warning restore 612, 618
        }
    }
}
